services:
  mysql:
    image: mysql:8.4
    container_name: payment-wallet-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: paymentdb
      MYSQL_USER: payment_user
      MYSQL_PASSWORD: payment_password
    ports:
      - "3306:3306"
    volumes:
      - payment_wallet_mysql_data:/var/lib/mysql

volumes:
  payment_wallet_mysql_data: