spring:
  application:
    name: payment-wallet-service

  profiles:
    active: local

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
